version: '3.9'
services:
  api:
    build:
      context: ./MenuService.Api
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MenuServiceDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
