name: Docker Tag and Push

on:
  push:
    branches:
      - master

jobs:
  tag-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image with `latest`
      - name: Build Docker Image
        run: |
          IMAGE_NAME="ellzup/menu-service"
          docker build -t $IMAGE_NAME:latest -f MenuService.Api/Dockerfile .

      # Step 4: Push Docker Image with `latest`
      - name: Push Docker Image
        run: |
          IMAGE_NAME="ellzup/menu-service"
          docker push $IMAGE_NAME:latest
