name: CI/CD with Docker Tagging

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0"

    # Restore dependencies och bygg projektet
    - name: Restore dependencies
      run: dotnet restore MenuService.Api/MenuService.Api.csproj

    - name: Build
      run: dotnet build MenuService.Api/MenuService.Api.csproj --configuration Release

    # Generera unik Docker tag
    - name: Set Image Tag
      run: echo "TAG_NAME=v$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    # Logga in på Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Bygg och pusha Docker-image
    - name: Build and push Docker image
      run: |
        IMAGE_NAME="your-dockerhub-username/menu-service"
        docker build -t $IMAGE_NAME:${{ env.TAG_NAME }} -f MenuService.Api/Dockerfile .
        docker push $IMAGE_NAME:${{ env.TAG_NAME }}
